[package]
name = "equation_eval"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.30"
equation_lexer = { path = "../lex" }
rust_decimal = { version = "1.23.1", default-features = false, features = ["maths-nopanic"] }

[features]
default = ["fmt"]
fmt = ["equation_lexer/fmt"]
